name: build
on:
  push:
    branches:
      - main
      - ci-20220103
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
env:
  JE2BE_DOCKER_CACHE_PATH: je2be_build_wasm.docker
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version-file: .node-version
          cache: yarn
      - name: Cache build directory
        uses: actions/cache@v2
        id: cache-build-directory
        with:
          path: build
          key: ${{ hashFiles('src/core/core.cpp', 'CMakeLists.txt', 'deps/**/*')}}
      - name: Touch restored build files
        if: steps.cache-build-directory.outputs.cache-hit == 'true'
        run: find build -type f | xargs touch
      - name: Cache docker image
        uses: actions/cache@v2
        id: cache-docker-image
        with:
          path: ${{ env.JE2BE_DOCKER_CACHE_PATH }}
          key: ${{ hashFiles('Dockerfile') }}
      - name: Build docker image
        if: steps.cache-docker-image.outputs.cache-hit != 'true'
        run: |
          make build_docker_image
          docker save je2be_build_wasm:latest -o ${JE2BE_DOCKER_CACHE_PATH}
      - run: docker load -i ${JE2BE_DOCKER_CACHE_PATH}
      - name: Build
        env:
          JE2BE_VERSION: ${{ github.ref_name }}
        run: |
          yarn install
          make all
      - name: Deploy
        if: github.ref_type == 'tag'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
