name: Build
on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
env:
  JE2BE_DOCKER_CACHE_PATH: je2be_build_wasm.docker
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: yarn
      - name: Cache build directory
        uses: actions/cache@v3
        id: cache-build-directory
        with:
          path: build
          key: ${{ hashFiles('src/**/*.cpp', 'CMakeLists.txt', 'deps/**/*', 'Dockerfile')}}
      - name: Touch restored build files
        if: steps.cache-build-directory.outputs.cache-hit == 'true'
        run: find build -type f | xargs touch
      - name: Cache docker image
        uses: actions/cache@v3
        id: cache-docker-image
        with:
          path: ${{ env.JE2BE_DOCKER_CACHE_PATH }}
          key: ${{ hashFiles('Dockerfile') }}
      - name: Build docker image
        if: steps.cache-docker-image.outputs.cache-hit != 'true'
        run: |
          make build_docker_image
          docker save je2be_build_wasm:latest -o ${JE2BE_DOCKER_CACHE_PATH}
      - run: docker load -i ${JE2BE_DOCKER_CACHE_PATH}
        if: steps.cache-docker-image.outputs.cache-hit == 'true'
      - name: Build
        env:
          JE2BE_VERSION: ${{ github.ref_name }}
        run: |
          yarn install
          make all
      - name: Deploy
        if: github.ref_type == 'tag'
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avc --delete
          path: public/
          remote_path: ${{ secrets.DEPLOY_DIR }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USERNAME }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
