name: build
on: push
env:
  JE2BE_DOCKER_CACHE_PATH
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache docker image
        uses: actions/cache@v2
        id: cache-docker-image
        with:
          path: ${{ env.JE2BE_DOCKER_CACHE_PATH }}
          key: ${{ hashFiles('Dockerfile') }}
      - name: Build docker image
        if: steps.cache-docker-image.outputs.cache-hit != 'true'
        run: |
          make build_docker_image
          docker save je2be_build_wasm:latest -o ${JE2BE_DOCKER_CACHE_PATH}
      - run: docker load -i ${JE2BE_DOCKER_CACHE_PATH}
      - run: make public/script/core.wasm
